# frozen_string_literal: true
require_relative 'inspecstyle/azure_generic_resource'
require_relative 'inspecstyle/shadow_properties'
require_relative 'inspecstyle/oracle_db_session_pass'
require_relative 'inspecstyle/file_size'
require_relative 'inspecstyle/apache'
require_relative 'inspecstyle/script_resource'
require_relative 'inspecstyle/users_resource_matchers'
require_relative 'inspecstyle/iis_website'
require_relative 'inspecstyle/host_proto'
require_relative 'inspecstyle/linux_kernel_parameter'
require_relative 'inspecstyle/mssql_session_pass'
require_relative 'inspecstyle/ppa_resource'
require_relative 'inspecstyle/processes_list'
require_relative 'inspecstyle/windows_registry_key'
require_relative 'inspecstyle/aws_iam_user_property'
require_relative 'inspecstyle/file_be_mounted'
require_relative 'inspecstyle/wmi_wmis_class'
require_relative 'inspecstyle/deprecated_attributes1'
# require_relative 'inspecstyle/deprecated_attributes'
