InSpecStyle/DeprecatedAttributes:
  Description: 'Attributes are deprecated in favor of inputs'
  Enabled: true
  VersionAdded: '0.82'

InspecStyle/FirstCop:
  Description: 'This first cop is a sandbox for exploring new InspecStyle cops.'
  Enabled: true
  VersionAdded: '0.82'
