InSpecStyle/Apache:
  Description: 'Use apache_conf instead of apache'
  Enabled: true
  VersionAdded: '0.82'
  PreferredReplacement: 'apache_conf'

InSpecStyle/AwsIamUserProperty:
  Description: 'For the aws_iam_users resource name and user properties are deprecated. Use username and aws_user_struct instead'
  Enabled: true
  VersionAdded: '0.82'

InSpecStyle/AzureGenericResource:
  Description: 'Do not use azure_generic_resource'
  Enabled: true
  VersionAdded: '0.82'
  StyleGuide: 'https://github.com/inspec/inspec/issues/3131'

InSpecStyle/DeprecatedAttributes1:
  Description: 'Attributes are deprecated in favor of inputs'
  Enabled: true
  VersionAdded: '0.82'
  StyleGuide: 'https://github.com/inspec/inspec/issues/3802'
  PreferredReplacement: 'input'

InSpecStyle/DeprecatedAttributes:
  Description: 'Attributes are deprecated in favor of inputs'
  Enabled: true
  VersionAdded: '0.82'
  StyleGuide: 'https://github.com/inspec/inspec/issues/3802'
  PreferredReplacement: 'input'

InSpecStyle/FileBeMounted:
  Description: 'aws_iam_users resource name and user properties are deprecated for username and aws_user_struct'
  Enabled: true
  VersionAdded: '0.82'

InSpecStyle/FileSize:
  Description: '`size` property for `file` resource is deprecated for `size_kb` and will be removed in InSpec5'
  Enabled: true
  VersionAdded: '0.82'
  PreferredReplacement: 'size_kb'

InSpecStyle/HostProto:
  Description: 'Proto property for host has been deprecated for protocol'
  Enabled: true
  VersionAdded: '0.82'
  PreferredReplacement: 'protocol'

InSpecStyle/IisWebsite:
  Description: 'iis_website resource has been deprecated for iis_site'
  Enabled: true
  VersionAdded: '0.82'
  PreferredReplacement: 'iis_site'

InSpecStyle/LinuxKernelParameter:
  Description: 'linux_kernel_parameter resource has been deprecated for kernel_parameter'
  Enabled: true
  VersionAdded: '0.82'
  PreferredReplacement: 'kernel_parameter'

InSpecStyle/MSSQLSessionPass:
  Description: 'mssql_session resource parameter pass is deprecated for password'
  Enabled: true
  VersionAdded: '0.82'

InSpecStyle/OracleDbSessionPass:
  Description: 'Use `password` instead of `pass`'
  Enabled: true
  VersionAdded: '0.82'
  PreferredReplacement: 'password'

InSpecStyle/PPAResource:
  Description: 'The ppa resource is deprecated in favor of the apt resource'
  Enabled: true
  VersionAdded: '0.82'
  PreferredReplacement: 'apt'

InSpecStyle/ProcessesList:
  Description: 'list property on processes resource is deprecated for entries'
  Enabled: true
  VersionAdded: '0.82'
  PreferredReplacement: 'entries'

InSpecStyle/ScriptResource:
  Description: 'Use powershell instead of script'
  Enabled: true
  VersionAdded: '0.82'
  PreferredReplacement: 'powershell'

InSpecStyle/ShadowProperties:
  Description: 'Deprecated properties for the shadow resource'
  Enabled: true
  VersionAdded: '0.82'

InSpecStyle/UsersResourceMatchers:
  Description: 'Deprecated matchers for the users resource'
  Enabled: true
  VersionAdded: '0.82'

InSpecStyle/WindowsRegistryKey:
  Description: 'The windows_registry_key resource is deprecated for registry_key'
  Enabled: true
  VersionAdded: '0.82'
  PreferredReplacement: 'registry_key'

InSpecStyle/WmiWmisClass:
  Description: "wmi('wmisclass') is deprecated for wmi({class: wmisclass})"
  Enabled: true
  VersionAdded: '0.82'
  PreferredReplacement: "wmi({class: 'wmisclass'})"
