InSpecStyle/AzureGenericResource:
  Description: 'Do not use azure_generic_resource'
  Enabled: true
  VersionAdded: '0.82'
  StyleGuide: 'https://github.com/inspec/inspec/issues/3131'

InSpecStyle/DeprecatedAttributes:
  Description: 'Attributes are deprecated in favor of inputs'
  Enabled: true
  VersionAdded: '0.82'
  StyleGuide: 'https://github.com/inspec/inspec/issues/3802'
  PreferredReplacement: 'input'

InSpecStyle/FileSize:
  Description: '`size` property for `file` resource is deprecated for `size_kb` and will be removed in InSpec5'
  Enabled: true
  VersionAdded: '0.86'
  PreferredReplacement: 'size_kb'

InSpecStyle/OracleDbSessionPass:
  Description: 'Use `password` instead of `pass`'
  Enabled: true
  VersionAdded: '0.82'
  PreferredReplacement: 'password'

InSpecStyle/ShadowProperties:
  Description: '`user` property for shadow resources is deprecated for `users`'
  Enabled: true
  VersionAdded: '0.82'

InspecStyle/FirstCop:
  Description: 'This first cop is a sandbox for exploring new InspecStyle cops.'
  Enabled: true
  VersionAdded: '0.82'
