InSpecStyle/AzureGenericResource:
  Description: 'Do not use azure_generic_resource'
  Enabled: true
  VersionAdded: '0.82'
  StyleGuide: 'https://github.com/inspec/inspec/issues/3131'

InSpecStyle/DeprecatedAttributes:
  Description: 'Attributes are deprecated in favor of inputs'
  Enabled: true
  VersionAdded: '0.82'
  StyleGuide: 'https://github.com/inspec/inspec/issues/3802'

InspecStyle/FirstCop:
  Description: 'This first cop is a sandbox for exploring new InspecStyle cops.'
  Enabled: true
  VersionAdded: '0.82'
