InSpecStyle/Apache:
  Description: 'Use apache_conf instead of apache'
  Enabled: true
  VersionAdded: '0.86'
  PreferredReplacement: 'apache_conf'

InSpecStyle/AzureGenericResource:
  Description: 'Do not use azure_generic_resource'
  Enabled: true
  VersionAdded: '0.82'
  StyleGuide: 'https://github.com/inspec/inspec/issues/3131'

InSpecStyle/DeprecatedAttributes:
  Description: 'Attributes are deprecated in favor of inputs'
  Enabled: true
  VersionAdded: '0.82'
  StyleGuide: 'https://github.com/inspec/inspec/issues/3802'
  PreferredReplacement: 'input'

InSpecStyle/FileSize:
  Description: '`size` property for `file` resource is deprecated for `size_kb` and will be removed in InSpec5'
  Enabled: true
  VersionAdded: '0.82'
  PreferredReplacement: 'size_kb'

InSpecStyle/OracleDbSessionPass:
  Description: 'Use `password` instead of `pass`'
  Enabled: true
  VersionAdded: '0.82'
  PreferredReplacement: 'password'

InSpecStyle/Script:
  Description: 'Use powershell instead of script'
  Enabled: true
  VersionAdded: '0.82'
  PreferredReplacement: 'powershell'

InSpecStyle/ShadowProperties:
  Description: 'Deprecated properties for the shadow resource'
  Enabled: true
  VersionAdded: '0.82'

InSpecStyle/UsersResourceMatchers:
  Description: 'Deprecated matchers for the users resource'
  Enabled: true
  VersionAdded: '0.82'
