name: Main

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1.40.0
      - run: bundle install
      - run: bundle exec rspec
