name: Main

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: setup bundler
        run: gem install bundler
      - name: bundle install
        run: bundle install
      - name: run the tests
        run: bundle exec rspec
